// Headless test of the Content Browser helpers (no GUI). Plain main +
// asserts, no framework, same pattern as physics_tests.cpp.
#include "DonTopo/Editor/ContentBrowserPanel.h"
#include "DonTopo/Editor/EditorContext.h"
#include "DonTopo/Editor/AssetImport.h"
#include "DonTopo/Editor/ProjectContext.h"
#include "DonTopo/Core/GameObject.h"
#include "DonTopo/Core/ImportSettings.h"
#include "DonTopo/Core/MaterialAsset.h"
#include "DonTopo/Renderer/Mesh.h"
#include "DonTopo/Renderer/ModelLoader.h"
#include "DonTopo/Renderer/SkinnedMesh.h"
#include "DonTopo/Core/AnimatorComponent.h"
#include "DonTopo/Editor/ModelReimport.h"
#include "DonTopo/Renderer/SkinnedMeshAnimations.h"
#include "DonTopo/Core/Scene.h"
#include "gltf_fixtures.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <glm/gtc/matrix_transform.hpp>
#include <memory>
#include <optional>
#include <sstream>
#include <system_error>
#include <vector>

using namespace DonTopo;
namespace fs = std::filesystem;

static int g_failures = 0;
#define CHECK(cond) do { if (!(cond)) { std::printf("FAIL: %s (line %d)\n", #cond, __LINE__); ++g_failures; } } while (0)

// Creates a temporary tree with normal folders, noise to filter out and a
// loose file. Returns the root.
static fs::path makeFixture()
{
    std::error_code ec;
    fs::path root = fs::temp_directory_path(ec) / "dt_content_browser_test";
    fs::remove_all(root, ec);
    fs::create_directories(root / "assets", ec);
    fs::create_directories(root / "Scripts", ec);
    fs::create_directories(root / ".hidden", ec);
    fs::create_directories(root / "build-ninja", ec);
    fs::create_directories(root / "cmake-build-debug", ec); // CLion
    // Name that no list contemplates, but with the CMakeCache inside: it is the
    // criterion that really decides (x64-Debug is generated by Visual Studio).
    fs::create_directories(root / "x64-Debug", ec);
    std::ofstream(root / "x64-Debug" / "CMakeCache.txt") << "x";
    // Name that STARTS with "build" but is not a build tree: it is shown.
    fs::create_directories(root / "build_assets", ec);
    // Generic build folder name, but WITHOUT CMakeCache: here it is a
    // user assets folder and it has to be shown (see isHiddenDir).
    fs::create_directories(root / "out", ec);
    std::ofstream(root / "readme.txt") << "x";
    return root;
}

// Lists only subfolders: no files, no hidden ones, no build trees.
static void test_filters_noise(const fs::path& root)
{
    std::vector<fs::path> dirs = listVisibleSubdirs(root);
    CHECK(dirs.size() == 4);
    if (dirs.size() == 4) {
        // std::sort on paths: 'S' (83) goes before the lowercase letters.
        CHECK(dirs[0].filename() == "Scripts");
        CHECK(dirs[1].filename() == "assets");
        // Neither the "build" prefix nor the suffix hides it: it has no CMakeCache.
        CHECK(dirs[2].filename() == "build_assets");
        CHECK(dirs[3].filename() == "out");
    }
}

// A folder with a build name but without a CMakeCache inside belongs to the user and is
// shown. It pins down the decision NOT to enumerate generic names: hiding "out" by
// name covered up one of the user's own assets folders.
static void test_generic_name_without_cache_is_visible(const fs::path& root)
{
    std::vector<fs::path> dirs = listVisibleSubdirs(root);
    bool encontrada = false;
    for (const auto& d : dirs)
        if (d.filename() == "out") encontrada = true;
    CHECK(encontrada);
}

// The criterion that rules is the content, not the name: a build folder with a
// name that is on no list is filtered all the same by its CMakeCache.txt.
// It pins down the difference from the previous version, which only knew "build-ninja".
static void test_hides_build_tree_by_content(const fs::path& root)
{
    std::vector<fs::path> dirs = listVisibleSubdirs(root);
    for (const auto& d : dirs)
        CHECK(d.filename() != "x64-Debug");
}

// Empty folders come out as such, not as an error.
static void test_empty_dir(const fs::path& root)
{
    CHECK(listVisibleSubdirs(root / "assets").empty());
}

// A nonexistent directory returns empty without throwing.
static void test_missing_dir(const fs::path& root)
{
    CHECK(listVisibleSubdirs(root / "no_existe_esta_carpeta").empty());
}

// A file (not a directory) returns empty without throwing.
static void test_path_is_file(const fs::path& root)
{
    CHECK(listVisibleSubdirs(root / "readme.txt").empty());
}

// GameObject with a SkinnedMesh (ModelLoader::loadSkinned) and a known texture path
// set by hand in materials[0] instead of the one the FBX brings: the
// goal of the following tests is to pin down the walk of materialsOf()
// (countSceneReferences/updateSceneReferencesForRename/
// detachSceneReferencesForDelete), not the specific content of the asset.
static std::unique_ptr<GameObject> makeSkinnedFixture(const std::string& texturePath)
{
    auto go = std::make_unique<GameObject>("Rigged");
    auto mesh = std::make_shared<SkinnedMesh>(ModelLoader::loadSkinned("assets/modelAnimation.fbx"));
    CHECK(!mesh->materials.empty());
    if (!mesh->materials.empty())
        mesh->materials[0].texturePath = texturePath;
    go->setMesh(mesh);
    return go;
}

// loadSkinned never populates the inherited Mesh::material (it hands out materials in
// SkinnedMesh::materials); looking only at material left this case returning
// 0 silently; this is exactly the "0 objects affected" that a rigged
// character saw in the destructive delete dialog before the fix.
static void test_count_references_finds_skinned_material_texture()
{
    const std::string knownPath = "assets/knownTexture.png";
    auto go = makeSkinnedFixture(knownPath);
    CHECK(countSceneReferences(go.get(), knownPath, /*isDir=*/false) == 1);
    CHECK(countSceneReferences(go.get(), std::string("assets/otraTextura.png"), false) == 0);
}

// The rename must rewrite the path inside SkinnedMesh::materials, not only
// in the inherited Mesh::material (which loadSkinned leaves empty).
static void test_rename_rewrites_skinned_material_path()
{
    const std::string oldPath = "assets/knownTexture.png";
    const std::string newPath = "assets/renamedTexture.png";
    auto go = makeSkinnedFixture(oldPath);
    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    updateSceneReferencesForRename(ctx, go.get(), oldPath, newPath, /*isDir=*/false);
    CHECK(go->getSkinnedMesh()->materials[0].texturePath == newPath);
}

// The detach must clear the path inside SkinnedMesh::materials before
// deleting the file from disk, so that a later re-register does not try
// stbi_load on an already deleted path.
static void test_detach_clears_skinned_material_path()
{
    const std::string knownPath = "assets/knownTexture.png";
    auto go = makeSkinnedFixture(knownPath);
    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    detachSceneReferencesForDelete(ctx, go.get(), knownPath, /*isDir=*/false);
    CHECK(go->getSkinnedMesh()->materials[0].texturePath.empty());
}

// The rename had the same blind spot with GameObject::materialOverrides that it
// used to have with SkinnedMesh::materials: it rewrote the Material IN MEMORY
// but not the override, which is what really survives a save
// (mesh.materials, Task 6). Without this, the serialized override kept
// pointing to the old name and the next Load did not find the texture;
// silent data loss. The three slots at once: the guard has to
// cover albedo, normal and orm, not just the first one tested.
static void test_rename_rewrites_material_override_path()
{
    const std::string oldPath = "assets/knownTexture.png";
    const std::string newPath = "assets/renamedTexture.png";
    auto go = makeSkinnedFixture(oldPath);
    MaterialOverride ov;
    ov.index  = 0;
    ov.albedo = oldPath;
    ov.normal = oldPath;
    ov.orm    = oldPath;
    go->materialOverrides.push_back(ov);

    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    updateSceneReferencesForRename(ctx, go.get(), oldPath, newPath, /*isDir=*/false);

    CHECK(go->materialOverrides[0].albedo == newPath);
    CHECK(go->materialOverrides[0].normal == newPath);
    CHECK(go->materialOverrides[0].orm    == newPath);
}

// Same case as above but for delete: the override that points to the file
// being deleted has to be emptied just like the Material, or the next Save
// rewrites the dead path and the next Load reapplies it over the material
// freshly derived from the FBX.
static void test_detach_clears_material_override_path()
{
    const std::string knownPath = "assets/knownTexture.png";
    auto go = makeSkinnedFixture(knownPath);
    MaterialOverride ov;
    ov.index  = 0;
    ov.albedo = knownPath;
    ov.normal = knownPath;
    ov.orm    = knownPath;
    go->materialOverrides.push_back(ov);

    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    detachSceneReferencesForDelete(ctx, go.get(), knownPath, /*isDir=*/false);

    CHECK(go->materialOverrides[0].albedo.empty());
    CHECK(go->materialOverrides[0].normal.empty());
    CHECK(go->materialOverrides[0].orm.empty());
}

static std::unique_ptr<GameObject> makeMatAssetFixture(const std::string& matPath)
{
    auto go = std::make_unique<GameObject>("ConMaterial");
    go->setMesh(std::make_shared<Mesh>());
    MaterialOverride ov; ov.index = 0; ov.matAsset = matPath;
    go->materialOverrides = {ov};
    return go;
}

// Review Focus 4.
static void test_count_references_finds_mat_asset()
{
    const std::string knownPath = "assets/rojo.mat";
    auto go = makeMatAssetFixture(knownPath);
    CHECK(countSceneReferences(go.get(), knownPath, /*isDir=*/false) == 1);
    CHECK(countSceneReferences(go.get(), std::string("assets/otro.mat"), false) == 0);
}

static void test_rename_rewrites_mat_asset_path()
{
    const std::string oldPath = "assets/rojo.mat";
    const std::string newPath = "assets/carmesi.mat";
    auto go = makeMatAssetFixture(oldPath);
    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    updateSceneReferencesForRename(ctx, go.get(), oldPath, newPath, /*isDir=*/false);
    CHECK(go->materialOverrides[0].matAsset == newPath);
}

// An object that does NOT use the renamed .mat is not touched.
static void test_rename_leaves_other_mat_asset_untouched()
{
    auto go = makeMatAssetFixture("assets/otro.mat");
    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    updateSceneReferencesForRename(ctx, go.get(), "assets/rojo.mat", "assets/carmesi.mat", false);
    CHECK(go->materialOverrides[0].matAsset == "assets/otro.mat");
}

// Review Focus 5: deleting the .mat in use empties matAsset AND the effective material
// goes back to the model's (it does not keep the last texture that the .mat brought).
// This requires applyMaterialOverrides + rebuild inside detachSceneReferencesForDelete,
// not just emptying the field: finding from the final reviewer, the previous test only
// checked matAsset.empty() and did not detect that the in-memory material
// kept the texture of the deleted .mat until the next reapplication.
static void test_detach_clears_mat_asset_and_falls_back_to_model()
{
    std::error_code ec;
    std::filesystem::path d = std::filesystem::temp_directory_path(ec) / "dt_matasset_detach_fallback";
    std::filesystem::remove_all(d, ec);
    std::filesystem::create_directories(d, ec);
    const std::string matPath = (d / "rojo.mat").string();

    MaterialAsset asset; asset.albedo = (d / "rojo.png").string();
    std::string err;
    CHECK(saveMaterialAsset(matPath, asset, &err));

    auto go = makeMatAssetFixture(matPath);
    go->editMesh()->material.texturePath = "assets/model_default.png";   // baseline that the FBX brings
    applyMaterialOverrides(*go);   // as in the real app: the .mat already resolved the slot
    CHECK(go->getMesh()->material.texturePath == asset.albedo);

    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    detachSceneReferencesForDelete(ctx, go.get(), matPath, /*isDir=*/false);

    CHECK(go->materialOverrides[0].matAsset.empty());
    CHECK(go->getMesh()->material.texturePath == "assets/model_default.png");
}

// The baseline (base*) pointing to the file that was just deleted was not a
// cosmetic detail: with the override empty and the *Taken flag raised,
// applyMaterialOverrides takes the "go back to the baseline" branch and REWRITES that
// dead path into the Material. And the next applyMaterialOverrides could be
// the one from editing any OTHER slot, so it silently undid the
// replaceStaticTextureWithMissing that the delete had just done.
//
// The flag stays raised on purpose (checked below): it is what makes
// the reapplication leave the slot EMPTY instead of resurrecting the deleted
// file.
static void test_detach_clears_material_override_baseline()
{
    const std::string knownPath = "assets/knownTexture.png";
    auto go = makeSkinnedFixture(knownPath);
    MaterialOverride ov;
    ov.index           = 0;
    ov.baseAlbedo      = knownPath;   // the user already did Clear: empty override,
    ov.baseAlbedoTaken = true;        // baseline taken and pointing to the file
    ov.baseNormal      = knownPath;
    ov.baseNormalTaken = true;
    ov.baseOrm         = knownPath;
    ov.baseOrmTaken    = true;
    go->materialOverrides.push_back(ov);

    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    detachSceneReferencesForDelete(ctx, go.get(), knownPath, /*isDir=*/false);

    CHECK(go->materialOverrides[0].baseAlbedo.empty());
    CHECK(go->materialOverrides[0].baseNormal.empty());
    CHECK(go->materialOverrides[0].baseOrm.empty());
    CHECK(go->materialOverrides[0].baseAlbedoTaken);

    // The proof that it mattered: reapplying now does NOT give the deleted
    // file back to the material. Before the fix, this line resurrected it.
    applyMaterialOverrides(*go);
    CHECK(go->getSkinnedMesh()->materials[0].texturePath.empty());
}

// The flip side of the rename: there the asset STILL exists under another name, so
// the baseline is corrected instead of thrown away. Without this, a later Clear
// gave the material back the old name, which no longer exists on disk.
static void test_rename_rewrites_material_override_baseline()
{
    const std::string oldPath = "assets/knownTexture.png";
    const std::string newPath = "assets/renamedTexture.png";
    auto go = makeSkinnedFixture(oldPath);
    MaterialOverride ov;
    ov.index           = 0;
    ov.albedo          = "assets/override.png";
    ov.baseAlbedo      = oldPath;
    ov.baseAlbedoTaken = true;
    ov.baseNormal      = oldPath;
    ov.baseNormalTaken = true;
    ov.baseOrm         = oldPath;
    ov.baseOrmTaken    = true;
    go->materialOverrides.push_back(ov);

    GameObject* selected = nullptr;
    bool isPlaying = false;
    EditorContext ctx{selected, isPlaying};
    updateSceneReferencesForRename(ctx, go.get(), oldPath, newPath, /*isDir=*/false);

    CHECK(go->materialOverrides[0].baseAlbedo == newPath);
    CHECK(go->materialOverrides[0].baseNormal == newPath);
    CHECK(go->materialOverrides[0].baseOrm    == newPath);
}

// importDroppedFilesInto: inside the rect it is imported, outside it is silently
// ignored, a non-importable extension is rejected, and a name conflict does not
// abort the rest of the batch (the four rules of the external drop design).
static void test_import_dropped_files_into(const fs::path& root)
{
    std::error_code ec;
    fs::path externalDir = root / "external_src";
    fs::create_directories(externalDir, ec);
    fs::path destDir = root / "import_dest";
    fs::create_directories(destDir, ec);

    std::ofstream(externalDir / "nuevo.png")     << "nuevo";
    std::ofstream(externalDir / "conflicto.png") << "version-nueva";
    std::ofstream(destDir     / "conflicto.png") << "version-vieja"; // already exists
    std::ofstream(externalDir / "notas.txt")     << "no importable";
    std::ofstream(externalDir / "lejos.png")     << "fuera del rect";

    const float rectX = 0.0f, rectY = 0.0f, rectW = 100.0f, rectH = 100.0f;
    std::vector<DroppedFile> dropped = {
        { externalDir / "nuevo.png",     50.0f, 50.0f },   // inside
        { externalDir / "conflicto.png", 50.0f, 50.0f },   // inside, conflict
        { externalDir / "notas.txt",     50.0f, 50.0f },   // inside, not importable
        { externalDir / "lejos.png",     500.0f, 500.0f }, // outside the rect
    };

    std::vector<AssetImportOutcome> outcomes =
        importDroppedFilesInto(dropped, rectX, rectY, rectW, rectH, destDir);

    // "lejos.png" does not even generate an entry: it fell outside the rect.
    CHECK(outcomes.size() == 3);
    if (outcomes.size() == 3)
    {
        CHECK(outcomes[0].result == AssetImportResult::Copied);
        CHECK(outcomes[0].destPath == destDir / "nuevo.png");
        CHECK(outcomes[1].result == AssetImportResult::RejectedNameConflict);
        CHECK(outcomes[2].result == AssetImportResult::RejectedExtension);
    }
    CHECK(fs::exists(destDir / "nuevo.png"));
    CHECK(!fs::exists(destDir / "lejos.png"));
    std::ifstream in(destDir / "conflicto.png");
    std::stringstream ss; ss << in.rdbuf();
    CHECK(ss.str() == "version-vieja"); // the conflict was not touched
}

// classifyAsset: a single classification for the grid icon and for the filter
// by type. Case does not matter; a folder is Folder even if it is named "a.png".
static void test_classify_asset()
{
    CHECK(classifyAsset(".fbx",  false) == AssetKind::Model3D);
    CHECK(classifyAsset(".GLB",  false) == AssetKind::Model3D);
    CHECK(classifyAsset(".obj",  false) == AssetKind::Model3D);
    CHECK(classifyAsset(".gltf", false) == AssetKind::Model3D);
    CHECK(classifyAsset(".dae",  false) == AssetKind::Other);    // not compiled: it is not promised
    CHECK(classifyAsset(".wav",  false) == AssetKind::Audio);
    CHECK(classifyAsset(".png",  false) == AssetKind::Image);
    CHECK(classifyAsset(".bmp",  false) == AssetKind::Image);
    CHECK(classifyAsset(".ttf",  false) == AssetKind::Font);
    CHECK(classifyAsset(".json", false) == AssetKind::Scene);
    CHECK(classifyAsset(".lua",  false) == AssetKind::Script);
    CHECK(classifyAsset(".spv",  false) == AssetKind::Shader);
    CHECK(classifyAsset(".xyz",  false) == AssetKind::Other);
    CHECK(classifyAsset("",      false) == AssetKind::Other);
    CHECK(classifyAsset(".png",  true)  == AssetKind::Folder);
}

// assetMatchesFilter: text = case-insensitive substring; type = exact
// equality; the two are combined with AND; "no filter" lets everything through.
static void test_asset_matches_filter()
{
    CHECK(assetMatchesFilter("Hero.fbx", AssetKind::Model3D, "", std::nullopt));
    CHECK(assetMatchesFilter("Hero.fbx", AssetKind::Model3D, "hero", std::nullopt));
    CHECK(assetMatchesFilter("Hero.fbx", AssetKind::Model3D, "RO.F", std::nullopt));
    CHECK(!assetMatchesFilter("Hero.fbx", AssetKind::Model3D, "villain", std::nullopt));
    CHECK(assetMatchesFilter("Hero.fbx", AssetKind::Model3D, "", AssetKind::Model3D));
    CHECK(!assetMatchesFilter("Hero.fbx", AssetKind::Model3D, "", AssetKind::Audio));
    // With a type chosen, folders are hidden (unless the type is Folder).
    CHECK(!assetMatchesFilter("Models", AssetKind::Folder, "", AssetKind::Model3D));
    CHECK(assetMatchesFilter("Models", AssetKind::Folder, "", AssetKind::Folder));
    // AND: the type matches but the text does not.
    CHECK(!assetMatchesFilter("Hero.fbx", AssetKind::Model3D, "villain", AssetKind::Model3D));
}

// uniqueFolderName: "Nueva carpeta", and if it exists "Nueva carpeta 2", "3"... without
// reusing the first gap in an ambiguous way.
static void test_unique_folder_name(const fs::path& root)
{
    std::error_code ec;
    fs::path dir = root / "unique_name_dir";
    fs::create_directories(dir, ec);

    CHECK(uniqueFolderName(dir) == "New Folder");
    fs::create_directories(dir / "New Folder", ec);
    CHECK(uniqueFolderName(dir) == "New Folder 2");
    fs::create_directories(dir / "New Folder 2", ec);
    CHECK(uniqueFolderName(dir) == "New Folder 3");
    // A FILE with that name also takes up the spot.
    std::ofstream(dir / "New Folder 3") << "x";
    CHECK(uniqueFolderName(dir) == "New Folder 4");
}

// breadcrumbSegments: from the project root to the current folder, with cumulative
// paths. Outside the root (or the root itself) only the root segment remains.
static void test_breadcrumb_segments(const fs::path& root)
{
    std::error_code ec;
    fs::path deep = root / "bc_assets" / "Imported";
    fs::create_directories(deep, ec);

    std::vector<BreadcrumbSegment> atRoot = breadcrumbSegments(root, root);
    CHECK(atRoot.size() == 1);
    if (atRoot.size() == 1)
    {
        CHECK(atRoot[0].name == root.filename().string());
        CHECK(atRoot[0].path == root);
    }

    std::vector<BreadcrumbSegment> nested = breadcrumbSegments(root, deep);
    CHECK(nested.size() == 3);
    if (nested.size() == 3)
    {
        CHECK(nested[0].path == root);
        CHECK(nested[1].name == "bc_assets");
        CHECK(nested[1].path == root / "bc_assets");
        CHECK(nested[2].name == "Imported");
        CHECK(nested[2].path == deep);
    }

    // A folder sibling to the root does not hang from it: only the root segment.
    std::vector<BreadcrumbSegment> outside =
        breadcrumbSegments(root, root.parent_path() / "otra_carpeta_ajena");
    CHECK(outside.size() == 1);
}

static std::string readAll(const fs::path& p)
{
    std::ifstream in(p);
    std::stringstream ss; ss << in.rdbuf();
    return ss.str();
}

// moveAsset: moves a file or folder to another folder, NEVER overwriting.
static void test_move_asset(const fs::path& root)
{
    std::error_code ec;
    fs::path base = root / "mv";
    fs::path dest = base / "dest";
    fs::create_directories(dest, ec);

    // File to another folder.
    std::ofstream(base / "a.png") << "contenido-a";
    MoveOutcome m1 = moveAsset(base / "a.png", dest);
    CHECK(m1.result == MoveResult::Moved);
    CHECK(m1.newPath == dest / "a.png");
    CHECK(!fs::exists(base / "a.png", ec));
    CHECK(readAll(dest / "a.png") == "contenido-a");

    // Folder with content.
    fs::create_directories(base / "folderX" / "sub", ec);
    std::ofstream(base / "folderX" / "inner.txt") << "dentro";
    MoveOutcome m2 = moveAsset(base / "folderX", dest);
    CHECK(m2.result == MoveResult::Moved);
    CHECK(m2.newPath == dest / "folderX");
    CHECK(readAll(dest / "folderX" / "inner.txt") == "dentro");
    CHECK(fs::exists(dest / "folderX" / "sub", ec));
    CHECK(!fs::exists(base / "folderX", ec));

    // It is already in that folder: there is nothing to move.
    MoveOutcome m3 = moveAsset(dest / "a.png", dest);
    CHECK(m3.result == MoveResult::RejectedSameFolder);
    CHECK(fs::exists(dest / "a.png", ec));

    // A folder cannot go into itself or into a descendant.
    MoveOutcome m4 = moveAsset(dest / "folderX", dest / "folderX");
    CHECK(m4.result == MoveResult::RejectedIntoSelf);
    MoveOutcome m5 = moveAsset(dest / "folderX", dest / "folderX" / "sub");
    CHECK(m5.result == MoveResult::RejectedIntoSelf);
    CHECK(fs::exists(dest / "folderX" / "inner.txt", ec));

    // Name conflict: rejects and touches neither the destination nor the source.
    fs::create_directories(base / "otra", ec);
    std::ofstream(base / "otra" / "a.png") << "version-nueva";
    MoveOutcome m6 = moveAsset(base / "otra" / "a.png", dest);
    CHECK(m6.result == MoveResult::RejectedNameConflict);
    CHECK(readAll(dest / "a.png") == "contenido-a");
    CHECK(readAll(base / "otra" / "a.png") == "version-nueva");

    // Nonexistent source.
    MoveOutcome m7 = moveAsset(base / "no_existe.png", dest);
    CHECK(m7.result == MoveResult::RejectedFailed);
    CHECK(!m7.errorMessage.empty());
}

static bool selectionIs(const AssetSelection& s, std::initializer_list<const char*> names)
{
    if (s.items.size() != names.size()) return false;
    size_t i = 0;
    for (const char* n : names)
        if (s.items[i++] != fs::path(n)) return false;
    return true;
}

// applyAssetClick: click = only that one; Ctrl = toggles; Shift = range from the anchor
// in VISIBLE order. The selected ones always remain in visible order.
static void test_apply_asset_click()
{
    const std::vector<fs::path> vis = { "a", "b", "c", "d", "e" };
    AssetSelection s;

    applyAssetClick(s, vis, "b", false, false);
    CHECK(selectionIs(s, {"b"}));
    CHECK(s.anchor && *s.anchor == fs::path("b"));

    applyAssetClick(s, vis, "d", true, false);          // Ctrl adds
    CHECK(selectionIs(s, {"b", "d"}));
    applyAssetClick(s, vis, "a", true, false);          // visible order, not click order
    CHECK(selectionIs(s, {"a", "b", "d"}));
    applyAssetClick(s, vis, "b", true, false);          // Ctrl on one already marked removes it
    CHECK(selectionIs(s, {"a", "d"}));
    CHECK(s.anchor && *s.anchor == fs::path("b"));      // the anchor is the last click

    applyAssetClick(s, vis, "c", false, false);         // a simple click replaces everything
    CHECK(selectionIs(s, {"c"}));
    applyAssetClick(s, vis, "e", false, true);          // Shift: range c..e
    CHECK(selectionIs(s, {"c", "d", "e"}));
    CHECK(s.anchor && *s.anchor == fs::path("c"));      // Shift does not move the anchor
    applyAssetClick(s, vis, "a", false, true);          // backward range: a..c
    CHECK(selectionIs(s, {"a", "b", "c"}));

    // Without an anchor, Shift behaves like a normal click.
    AssetSelection empty;
    applyAssetClick(empty, vis, "d", false, true);
    CHECK(selectionIs(empty, {"d"}));

    // Anchor that is no longer visible (a filter hid it): also a normal click.
    AssetSelection stale;
    stale.items  = { "z" };
    stale.anchor = fs::path("z");
    applyAssetClick(stale, vis, "c", false, true);
    CHECK(selectionIs(stale, {"c"}));
}

// pruneSelection: removes what no longer exists; if the anchor disappears, it is forgotten.
static void test_prune_selection()
{
    AssetSelection s;
    s.items  = { "a", "b", "c" };
    s.anchor = fs::path("b");
    pruneSelection(s, { "a", "c", "d" });
    CHECK(selectionIs(s, {"a", "c"}));
    CHECK(!s.anchor);
    CHECK(s.contains("a"));
    CHECK(!s.contains("b"));
}

// listVisibleEntries: visible files and folders of ONE folder, sorted; the
// hidden / build folders are left out just as in the tree. It is what the
// polling compares between passes to know whether something changed outside the editor.
static void test_list_visible_entries(const fs::path& root)
{
    std::error_code ec;
    fs::path dir = root / "lve";
    fs::create_directories(dir / "sub", ec);
    fs::create_directories(dir / ".hidden", ec);
    fs::create_directories(dir / "build-ninja", ec);
    std::ofstream(dir / "b.txt") << "x";
    std::ofstream(dir / "a.txt") << "x";

    std::vector<fs::path> before = listVisibleEntries(dir);
    CHECK(before.size() == 3);
    if (before.size() == 3)
    {
        CHECK(before[0].filename() == "a.txt");
        CHECK(before[1].filename() == "b.txt");
        CHECK(before[2].filename() == "sub");
    }

    // Someone creates a file from outside: the next read already brings it.
    std::ofstream(dir / "c.txt") << "x";
    std::vector<fs::path> afterCreate = listVisibleEntries(dir);
    CHECK(afterCreate.size() == 4);
    CHECK(afterCreate != before);

    // ...and someone else deletes it.
    fs::remove(dir / "a.txt", ec);
    std::vector<fs::path> afterRemove = listVisibleEntries(dir);
    CHECK(afterRemove.size() == 3);
    CHECK(afterRemove != afterCreate);

    // Without changes, two equal reads (it is what avoids a false refresh).
    CHECK(listVisibleEntries(dir) == afterRemove);

    // Nonexistent folder or a file: empty, without throwing.
    CHECK(listVisibleEntries(dir / "no_existe").empty());
    CHECK(listVisibleEntries(dir / "b.txt").empty());
}

// nearestExistingDir: if the current folder disappears from outside, the panel goes up to the
// nearest existing ancestor without leaving the project root.
static void test_nearest_existing_dir(const fs::path& root)
{
    std::error_code ec;
    fs::path a = root / "ned" / "a";
    fs::create_directories(a, ec);

    CHECK(nearestExistingDir(a, root) == a);                         // exists: itself
    CHECK(nearestExistingDir(a / "b" / "c", root) == a);             // two levels missing
    CHECK(nearestExistingDir(root / "ned" / "x", root) == root / "ned");
    CHECK(nearestExistingDir(root / "zzz" / "y", root) == root);     // everything missing up to the root
    CHECK(nearestExistingDir(root, root) == root);
    CHECK(nearestExistingDir(root.parent_path() / "ajena", root) == root); // outside the root
}

static TextureImportSettings mipsOn()
{
    TextureImportSettings s;
    s.mipmaps = true;
    return s;
}

static void test_list_hides_import_sidecars()
{
    std::error_code ec;
    const fs::path dir = fs::temp_directory_path(ec) / "dt_cb_sidecar_list";
    fs::remove_all(dir, ec);
    fs::create_directories(dir, ec);
    std::ofstream(dir / "foto.png") << "x";
    std::ofstream(dir / "escena.json") << "{}";
    std::string err;
    CHECK(saveTextureImportSettings(dir / "foto.png", mipsOn(), &err));
    CHECK(fs::exists(importSidecarPath(dir / "foto.png")));

    const std::vector<fs::path> entries = listVisibleEntries(dir);
    CHECK(entries.size() == 2);                       // foto.png and escena.json, NOT the sidecar
    for (const fs::path& p : entries)
        CHECK(!isImportSidecar(p));
}

static void test_move_asset_carries_sidecar()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_sidecar_move";
    fs::remove_all(base, ec);
    fs::create_directories(base / "A", ec);
    fs::create_directories(base / "B", ec);
    std::ofstream(base / "A" / "foto.png") << "x";
    std::string err;
    CHECK(saveTextureImportSettings(base / "A" / "foto.png", mipsOn(), &err));

    const MoveOutcome m = moveAsset(base / "A" / "foto.png", base / "B");
    CHECK(m.result == MoveResult::Moved);
    CHECK(fs::exists(base / "B" / "foto.png"));
    CHECK(loadTextureImportSettings(base / "B" / "foto.png") == mipsOn());
    CHECK(!fs::exists(importSidecarPath(base / "A" / "foto.png")));
}

// Finding from the final reviewer: the texture paths of a .mat are stored
// RELATIVE TO ITS OWN FOLDER (MaterialAsset.cpp). Moving the .mat without
// rewriting them leaves them resolved against the new folder, which is not where
// the texture is.
static void test_move_asset_rewrites_mat_relative_texture()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_mat_move";
    fs::remove_all(base, ec);
    fs::create_directories(base / "A", ec);
    fs::create_directories(base / "A" / "Metal", ec);
    fs::create_directories(base / "B", ec);

    const fs::path texture = base / "A" / "rojo.png";
    std::ofstream(texture) << "x";
    MaterialAsset asset; asset.albedo = texture.string();   // absolute in memory
    std::string err;
    CHECK(saveMaterialAsset(base / "A" / "x.mat", asset, &err));

    // The texture stays OUTSIDE the destination folder: moving the .mat to B has
    // to keep pointing to A/rojo.png, not to B/rojo.png.
    const MoveOutcome m = moveAsset(base / "A" / "x.mat", base / "B");
    CHECK(m.result == MoveResult::Moved);
    CHECK(fs::exists(base / "B" / "x.mat"));
    const MaterialAsset reloaded = loadMaterialAsset(base / "B" / "x.mat");
    CHECK(fs::equivalent(reloaded.albedo, texture, ec));
}

// Review Focus 4.
static void test_move_asset_rejects_when_destination_sidecar_exists()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_sidecar_move_conflict";
    fs::remove_all(base, ec);
    fs::create_directories(base / "A", ec);
    fs::create_directories(base / "B", ec);
    std::ofstream(base / "A" / "foto.png") << "x";
    std::string err;
    CHECK(saveTextureImportSettings(base / "A" / "foto.png", mipsOn(), &err));
    // ORPHAN sidecar at the destination: the photo does not exist there, its sidecar does.
    TextureImportSettings other;
    other.colorSpace = ColorSpaceOverride::Linear;
    CHECK(saveTextureImportSettings(base / "B" / "foto.png", other, &err));

    const MoveOutcome m = moveAsset(base / "A" / "foto.png", base / "B");
    CHECK(m.result == MoveResult::RejectedNameConflict);
    CHECK(fs::exists(base / "A" / "foto.png"));
    CHECK(loadTextureImportSettings(base / "A" / "foto.png") == mipsOn());     // source intact
    CHECK(loadTextureImportSettings(base / "B" / "foto.png") == other);        // destination not overwritten
    CHECK(!fs::exists(base / "B" / "foto.png"));
}

static void test_rename_asset_file_carries_sidecar_and_rejects_conflict()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_sidecar_rename";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    std::ofstream(base / "x.png") << "x";
    std::string err;
    CHECK(saveTextureImportSettings(base / "x.png", mipsOn(), &err));

    RenameFileOutcome r = renameAssetFile(base / "x.png", base / "y.png", false);
    CHECK(r.ok);
    CHECK(r.warning.empty());
    CHECK(fs::exists(base / "y.png"));
    CHECK(loadTextureImportSettings(base / "y.png") == mipsOn());
    CHECK(!fs::exists(importSidecarPath(base / "x.png")));

    // The destination already has a sidecar (orphan): it is rejected without touching anything.
    std::ofstream(base / "z.png") << "z";
    CHECK(saveTextureImportSettings(base / "z.png", mipsOn(), &err));
    fs::remove(base / "z.png", ec);                                  // only the sidecar is left
    r = renameAssetFile(base / "y.png", base / "z.png", false);
    CHECK(!r.ok);
    CHECK(!r.error.empty());
    CHECK(fs::exists(base / "y.png"));
    CHECK(loadTextureImportSettings(base / "y.png") == mipsOn());
    CHECK(!fs::exists(base / "z.png"));

    // A folder is renamed without looking at sidecars.
    fs::create_directories(base / "dirA", ec);
    r = renameAssetFile(base / "dirA", base / "dirB", true);
    CHECK(r.ok);
    CHECK(fs::is_directory(base / "dirB"));
}

// Final review fix: on a case-insensitive file system
// (NTFS), renaming "foto.png" to "Foto.png" has the SAME sidecar at source and
// destination: that is not a conflict, it is the same file.
static void test_rename_asset_file_case_only_is_not_a_sidecar_conflict()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_sidecar_rename_case";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    std::ofstream(base / "foto.png") << "x";
    std::string err;
    CHECK(saveTextureImportSettings(base / "foto.png", mipsOn(), &err));

    const RenameFileOutcome r = renameAssetFile(base / "foto.png", base / "Foto.png", false);
    CHECK(r.ok);
    CHECK(r.error.empty());
    CHECK(loadTextureImportSettings(base / "Foto.png") == mipsOn());   // the settings are still there
}

// Review Focus 5.
static void test_remove_asset_path_removes_sidecar()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_sidecar_remove";
    fs::remove_all(base, ec);
    fs::create_directories(base / "carpeta" / "sub", ec);
    std::ofstream(base / "foto.png") << "x";
    std::ofstream(base / "carpeta" / "sub" / "t.png") << "x";
    std::string err;
    CHECK(saveTextureImportSettings(base / "foto.png", mipsOn(), &err));
    CHECK(saveTextureImportSettings(base / "carpeta" / "sub" / "t.png", mipsOn(), &err));

    CHECK(!removeAssetPath(base / "foto.png", false));
    CHECK(!fs::exists(base / "foto.png"));
    CHECK(!fs::exists(importSidecarPath(base / "foto.png")));

    CHECK(!removeAssetPath(base / "carpeta", true));
    CHECK(!fs::exists(base / "carpeta"));

    // An ORPHAN sidecar gives no error when listing or when moving another asset.
    CHECK(saveTextureImportSettings(base / "fantasma.png", mipsOn(), &err));
    CHECK(listVisibleEntries(base).empty());
    std::ofstream(base / "otra.png") << "x";
    fs::create_directories(base / "dest", ec);
    CHECK(moveAsset(base / "otra.png", base / "dest").result == MoveResult::Moved);
}

static std::shared_ptr<Mesh> meshWithTexture(const fs::path& tex)
{
    auto m = std::make_shared<Mesh>();
    m->material.texturePath = tex.string();
    return m;
}

static void test_apply_writes_sidecar_and_rebuilds_only_users()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    const fs::path foto = base / "foto.png";
    const fs::path otra = base / "otra.png";
    std::ofstream(foto) << "x";
    std::ofstream(otra) << "x";

    GameObject root("root");
    GameObject* a = root.addChild("A");
    GameObject* b = root.addChild("B");
    root.addChild("C");                         // without a mesh
    a->setMesh(meshWithTexture(foto));
    b->setMesh(meshWithTexture(otra));

    std::vector<GameObject*> rebuilt;
    const auto rebuild = [&](GameObject& go) { rebuilt.push_back(&go); };

    TextureImportSettings s;
    s.colorSpace = ColorSpaceOverride::Linear;
    s.mipmaps    = true;
    TextureImportApplyResult r = applyTextureImportSettings(&root, foto, s, rebuild);
    CHECK(r.ok);
    CHECK(r.error.empty());
    CHECK(r.refreshed == 1);
    CHECK(rebuilt.size() == 1 && rebuilt[0] == a);
    CHECK(loadTextureImportSettings(foto) == s);

    // With the default: it deletes the sidecar and keeps rebuilding the one that uses it.
    rebuilt.clear();
    r = applyTextureImportSettings(&root, foto, TextureImportSettings{}, rebuild);
    CHECK(r.ok);
    CHECK(r.refreshed == 1);
    CHECK(rebuilt.size() == 1 && rebuilt[0] == a);
    CHECK(!fs::exists(importSidecarPath(foto)));
}

// Review Focus 6.
static void test_apply_reports_write_failure_and_rebuilds_nothing()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_fail";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    const fs::path foto = base / "no_existe_carpeta" / "foto.png";     // the sidecar cannot be written

    GameObject root("root");
    root.addChild("A")->setMesh(meshWithTexture(foto));

    int calls = 0;
    TextureImportSettings s;
    s.mipmaps = true;
    const TextureImportApplyResult r =
        applyTextureImportSettings(&root, foto, s, [&](GameObject&) { ++calls; });
    CHECK(!r.ok);
    CHECK(!r.error.empty());
    CHECK(r.refreshed == 0);
    CHECK(calls == 0);
}

static void test_apply_without_renderer_still_writes()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_norender";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    const fs::path foto = base / "foto.png";
    std::ofstream(foto) << "x";

    GameObject root("root");
    root.addChild("A")->setMesh(meshWithTexture(foto));

    TextureImportSettings s;
    s.mipmaps = true;
    const TextureImportApplyResult r = applyTextureImportSettings(&root, foto, s, {});
    CHECK(r.ok);
    CHECK(r.refreshed == 0);
    CHECK(loadTextureImportSettings(foto) == s);
}

static void test_apply_audio_writes_sidecar_and_refreshes_once()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_audio";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    const fs::path clip = base / "disparo.wav";
    std::ofstream(clip) << "wav";

    std::vector<std::string> refreshed;
    const auto refresh = [&](const std::string& p) { refreshed.push_back(p); };

    AudioImportSettings s;
    s.gainDb    = -4.0f;
    s.forceMono = true;
    AudioImportApplyResult r = applyAudioImportSettings(clip, s, refresh);
    CHECK(r.ok);
    CHECK(r.error.empty());
    CHECK(refreshed.size() == 1 && refreshed[0] == clip.string());
    CHECK(loadAudioImportSettings(clip) == s);

    // The default deletes the sidecar and still refreshes (the voice goes back to its volume).
    r = applyAudioImportSettings(clip, AudioImportSettings{}, refresh);
    CHECK(r.ok);
    CHECK(refreshed.size() == 2);
    CHECK(!fs::exists(importSidecarPath(clip)));
}

// Review Focus 8: if the sidecar cannot be written, nothing is refreshed.
static void test_apply_audio_write_failure_does_not_refresh()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_audio_fail";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    int calls = 0;
    AudioImportSettings s;
    s.gainDb = 3.0f;
    const AudioImportApplyResult r = applyAudioImportSettings(
        base / "no_existe_carpeta" / "x.wav", s, [&](const std::string&) { ++calls; });
    CHECK(!r.ok);
    CHECK(!r.error.empty());
    CHECK(calls == 0);
}

static void test_apply_audio_without_audio_manager_still_writes()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_audio_norefresh";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    const fs::path clip = base / "a.wav";
    std::ofstream(clip) << "wav";
    AudioImportSettings s;
    s.forceMono = true;
    const AudioImportApplyResult r = applyAudioImportSettings(clip, s, {});
    CHECK(r.ok);
    CHECK(loadAudioImportSettings(clip) == s);
}

// Review Focus 8: which assets offer "Import Settings...".
static void test_import_settings_menu_kind()
{
    CHECK(importSettingsKindFor(".png", false)  == ImportSettingsKind::Texture);
    CHECK(importSettingsKindFor(".WAV", false)  == ImportSettingsKind::Audio);
    CHECK(importSettingsKindFor(".mp3", false)  == ImportSettingsKind::Audio);
    CHECK(importSettingsKindFor(".ogg", false)  == ImportSettingsKind::Audio);
    CHECK(importSettingsKindFor(".flac", false) == ImportSettingsKind::Audio);
    CHECK(importSettingsKindFor(".fbx", false)  == ImportSettingsKind::Model);
    CHECK(importSettingsKindFor(".GLB", false)  == ImportSettingsKind::Model);   // any 3D model
    CHECK(importSettingsKindFor(".fbx", true)   == ImportSettingsKind::None);    // a folder
    CHECK(importSettingsKindFor(".lua", false)  == ImportSettingsKind::None);
    CHECK(importSettingsKindFor(".wav", true)   == ImportSettingsKind::None);   // a folder
}

static void test_classify_material_extension()
{
    CHECK(classifyAsset(".mat", false) == AssetKind::Material);
    CHECK(classifyAsset(".MAT", false) == AssetKind::Material);
    CHECK(classifyAsset(".mat", true)  == AssetKind::Folder);   // a folder rules
}

// Finding from the final reviewer: the Browse of the .mat edit modal
// accepted an absolute path from outside the project as is; that .mat travels
// with it and the exported game stops finding the texture on another machine.
static void test_accept_or_import_mat_texture_imports_external_path()
{
    std::error_code ec;
    const fs::path projectRoot = fs::temp_directory_path(ec) / "dt_cb_matimport_project";
    const fs::path outside     = fs::temp_directory_path(ec) / "dt_cb_matimport_outside";
    fs::remove_all(projectRoot, ec);
    fs::remove_all(outside, ec);
    fs::create_directories(projectRoot, ec);
    fs::create_directories(outside, ec);
    std::ofstream(outside / "textura.png") << "x";

    ProjectContext project(projectRoot);
    const auto imported = acceptOrImportMatTexture(&project, outside / "textura.png");
    CHECK(imported.has_value());
    if (imported)
    {
        CHECK(project.contains(*imported));
        CHECK(fs::exists(*imported));
    }
}

// A path that is ALREADY inside the project is returned as is (without copying
// a second time).
static void test_accept_or_import_mat_texture_leaves_internal_path()
{
    std::error_code ec;
    const fs::path projectRoot = fs::temp_directory_path(ec) / "dt_cb_matimport_internal";
    fs::remove_all(projectRoot, ec);
    fs::create_directories(projectRoot / "assets", ec);
    std::ofstream(projectRoot / "assets" / "textura.png") << "x";

    ProjectContext project(projectRoot);
    const auto result = acceptOrImportMatTexture(&project, projectRoot / "assets" / "textura.png");
    CHECK(result.has_value());
    if (result) CHECK(fs::equivalent(*result, projectRoot / "assets" / "textura.png", ec));
}

// Without a project (headless tests, or the .mat is edited before choosing one) it is
// accepted as is, like the rest of the editor without an open project.
static void test_accept_or_import_mat_texture_without_project_passes_through()
{
    const fs::path anyPath = "C:/no/existe/x.png";
    const auto result = acceptOrImportMatTexture(nullptr, anyPath);
    CHECK(result.has_value());
    if (result) CHECK(*result == anyPath);
}

// Finding from the final reviewer: a loose .mat could not be dragged from the
// grid (isImportableExtension does not cover it, because a .mat is never imported
// from outside the project), so neither "Drop .mat here" in Properties nor moving
// a .mat to another folder by dragging it worked.
static void test_material_is_draggable()
{
    CHECK(isAssetDraggable(".mat", /*isDir=*/false, /*inMultiSelection=*/false));
    CHECK(isAssetDraggable(".MAT", false, false));
    CHECK(!isAssetDraggable(".unknownext", false, false));
    CHECK(isAssetDraggable(".unknownext", false, /*inMultiSelection=*/true));
    CHECK(isAssetDraggable("", /*isDir=*/true, false));
}

static void test_unique_material_name()
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / "dt_cb_unique_mat";
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    CHECK(uniqueMaterialName(d) == "New Material.mat");
    std::ofstream(d / "New Material.mat") << "x";
    CHECK(uniqueMaterialName(d) == "New Material 2.mat");
}

// applyMaterialAssetSettings writes the file and rebuilds ONLY whoever
// references that .mat, whatever the object is (Review Focus 2: several users).
static void test_apply_material_asset_writes_and_refreshes_all_users()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_mat";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    const fs::path mat = base / "x.mat";
    std::string err;
    CHECK(saveMaterialAsset(mat, MaterialAsset{}, &err));

    GameObject root("root");
    GameObject* a = root.addChild("A");
    GameObject* b = root.addChild("B");
    GameObject* c = root.addChild("C");   // no usa el .mat
    a->setMesh(std::make_shared<Mesh>());
    b->setMesh(std::make_shared<Mesh>());
    c->setMesh(std::make_shared<Mesh>());
    MaterialOverride ovA; ovA.matAsset = mat.string();
    a->materialOverrides = {ovA};
    MaterialOverride ovB; ovB.matAsset = mat.string();
    b->materialOverrides = {ovB};

    std::vector<GameObject*> rebuilt;
    const auto rebuild = [&](GameObject& go) { rebuilt.push_back(&go); };

    MaterialAsset s; s.roughness = 0.3f;
    const MaterialAssetApplyResult r = applyMaterialAssetSettings(&root, mat, s, rebuild);
    CHECK(r.ok);
    CHECK(r.error.empty());
    CHECK(r.refreshed == 2);
    CHECK(rebuilt.size() == 2);
    CHECK((rebuilt[0] == a && rebuilt[1] == b) || (rebuilt[0] == b && rebuilt[1] == a));
    CHECK(loadMaterialAsset(mat) == s);
    CHECK(a->getMesh()->material.roughness == 0.3f);
    CHECK(c->getMesh()->material.roughness == 0.5f);   // the Material default, untouched
}

// User report: "when opening the material it does not save what was added, for
// example the albedo". EXACT same path as Apply in the modal: save
// via applyMaterialAssetSettings and re-read via loadMaterialAsset (what the
// double click does on reopening), with an ABSOLUTE texture like the one left by
// acceptOrImportMatTexture/a drag from the grid.
static void test_apply_material_asset_albedo_survives_reopen()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_mat_albedo";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    const fs::path mat = base / "x.mat";
    const fs::path tex = base / "rojo.png";
    std::ofstream(tex) << "x";
    std::string err;
    CHECK(saveMaterialAsset(mat, MaterialAsset{}, &err));

    MaterialAsset edit = loadMaterialAsset(mat);   // what the double click does on opening
    edit.albedo = tex.string();                    // what Browse/drop leaves in the modal

    const MaterialAssetApplyResult r = applyMaterialAssetSettings(nullptr, mat, edit, nullptr);
    CHECK(r.ok);
    CHECK(r.error.empty());

    const MaterialAsset reopened = loadMaterialAsset(mat);   // reopen the .mat
    CHECK(fs::equivalent(reopened.albedo, tex, ec));
}

// Review Focus (write): a write failure rebuilds nothing.
static void test_apply_material_asset_write_failure_rebuilds_nothing()
{
    std::error_code ec;
    const fs::path base = fs::temp_directory_path(ec) / "dt_cb_apply_mat_fail";
    fs::remove_all(base, ec);
    fs::create_directories(base, ec);
    GameObject root("root");
    root.addChild("A");
    int calls = 0;
    const MaterialAssetApplyResult r = applyMaterialAssetSettings(
        &root, base / "no_existe_carpeta" / "x.mat", MaterialAsset{}, [&](GameObject&) { ++calls; });
    CHECK(!r.ok);
    CHECK(!r.error.empty());
    CHECK(r.refreshed == 0);
    CHECK(calls == 0);
}

// ── reimportModelUsers ───────────────────────────────────────────────────────

static fs::path writeTriangleObj(const char* dirName)
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / dirName;
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    const fs::path obj = d / "tri.obj";
    std::ofstream(obj) << "v 0 0 0\nv 1 0 0\nv 0 1 0\nvt 0 0\nvt 1 0\nvt 0 1\nf 1/1 2/2 3/3\n";
    return obj;
}

static float maxAbsX(const Mesh& m)
{
    float r = 0.0f;
    for (const Vertex& v : m.vertices) r = std::max(r, std::abs(v.pos.x));
    return r;
}

// The objects of that FBX are reloaded with the new settings; the others are not even touched.
static void test_reimport_replaces_the_meshes_of_that_fbx_only()
{
    const fs::path obj = writeTriangleObj("dt_cb_reimport_static");
    GameObject root("root");
    GameObject* a = root.addChild("A");
    GameObject* b = root.addChild("B");
    GameObject* c = root.addChild("C");   // procedural: no sourcePath
    a->setMesh(ModelLoader::loadAuto(obj.string()));
    b->setMesh(ModelLoader::loadAuto(obj.string()));
    c->setMesh(std::make_shared<Mesh>());
    CHECK(maxAbsX(*a->getMesh()) == 1.0f);

    // A texture override on object A: it has to survive the reimport.
    MaterialOverride ov;
    ov.index  = 0;
    ov.albedo = "assets/x.png";
    a->materialOverrides = { ov };

    ModelImportSettings s;
    s.scale = 2.0f;
    std::string err;
    CHECK(saveModelImportSettings(obj, s, &err));

    const ModelReimportResult r = reimportModelUsers(&root, obj, nullptr);
    CHECK(r.reimported == 2);
    CHECK(r.skipped == 0);
    CHECK(r.warnings.empty());
    CHECK(maxAbsX(*a->getMesh()) == 2.0f);
    CHECK(maxAbsX(*b->getMesh()) == 2.0f);
    CHECK(c->getMesh()->sourcePath.empty());                          // it was not from that FBX
    CHECK(a->getMesh()->sourcePath == obj.string());
    CHECK(a->materialOverrides[0].albedo == "assets/x.png");
    CHECK(a->getMesh()->material.texturePath == "assets/x.png");      // reapplied on the new mesh
}

// Review Focus 2: the FBX no longer loads -> the objects stay as they were.
static void test_reimport_of_an_unloadable_fbx_leaves_the_objects_intact()
{
    const fs::path obj = writeTriangleObj("dt_cb_reimport_missing");
    GameObject root("root");
    GameObject* a = root.addChild("A");
    a->setMesh(ModelLoader::loadAuto(obj.string()));
    const Mesh* antes = a->getMesh().get();

    std::error_code ec;
    fs::remove(obj, ec);                                               // the file disappears

    const ModelReimportResult r = reimportModelUsers(&root, obj, nullptr);
    CHECK(r.reimported == 0);
    CHECK(r.skipped == 1);
    CHECK(r.warnings.size() == 1);
    CHECK(a->hasMesh());
    CHECK(a->getMesh().get() == antes);
    CHECK(maxAbsX(*a->getMesh()) == 1.0f);
}

// Without users there is nothing to do or to warn about.
static void test_reimport_without_users_is_a_noop()
{
    const fs::path obj = writeTriangleObj("dt_cb_reimport_nousers");
    GameObject root("root");
    root.addChild("A")->setMesh(std::make_shared<Mesh>());
    const ModelReimportResult r = reimportModelUsers(&root, obj, nullptr);
    CHECK(r.reimported == 0 && r.skipped == 0 && r.warnings.empty());
    const ModelReimportResult r2 = reimportModelUsers(nullptr, obj, nullptr);
    CHECK(r2.reimported == 0 && r2.skipped == 0);
}

// Defensive: an object with a mesh and at the same time with an asynchronous load in flight is
// not touched (same criterion as MeshComponentCommand::put).
static void test_reimport_skips_an_object_with_a_pending_load()
{
    const fs::path obj = writeTriangleObj("dt_cb_reimport_pending");
    GameObject root("root");
    GameObject* a = root.addChild("A");
    a->setMesh(ModelLoader::loadAuto(obj.string()));
    a->pendingMeshJob = 7;

    ModelImportSettings s;
    s.scale = 2.0f;
    std::string err;
    CHECK(saveModelImportSettings(obj, s, &err));

    const ModelReimportResult r = reimportModelUsers(&root, obj, nullptr);
    CHECK(r.reimported == 0);
    CHECK(r.skipped == 1);
    CHECK(r.warnings.size() == 1);
    CHECK(maxAbsX(*a->getMesh()) == 1.0f);
}

// Review Focus 3: a character with a renamed clip, external source and Animator.
static void test_reimport_skinned_keeps_the_animation_config_and_rebinds()
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / "dt_cb_reimport_skinned";
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    const fs::path fbx = d / "char.fbx";
    fs::copy_file("assets/modelAnimation.fbx", fbx, fs::copy_options::overwrite_existing, ec);
    CHECK(!ec);

    auto mesh = std::make_shared<SkinnedMesh>(ModelLoader::loadSkinned(fbx.string()));
    std::vector<std::string> w;
    CHECK(addAnimationSource(*mesh, fbx.string(), w));
    CHECK(mesh->animationSources.size() == 2u);
    if (mesh->animationSources.size() != 2u) return;
    CHECK(renameClip(*mesh, mesh->animationSources[0].clipNames[0], "CaminarRenombrado"));
    CHECK(renameClip(*mesh, mesh->animationSources[1].clipNames[0], "SaltoRenombrado"));
    const float extentAntes = [&] {
        float r = 0.0f;
        for (const SkinnedVertex& v : mesh->skinnedVertices) r = std::max(r, std::abs(v.position.x));
        return r;
    }();

    GameObject root("root");
    GameObject* go = root.addChild("Personaje");
    go->setMesh(mesh);
    auto anim = std::make_shared<AnimatorComponent>();
    AnimatorComponent::State st;
    st.name = "Salto"; st.clipName = "SaltoRenombrado";
    anim->addState(st);
    go->setAnimator(anim);

    ModelImportSettings s;
    s.scale = 2.0f;
    std::string err;
    CHECK(saveModelImportSettings(fbx, s, &err));

    const ModelReimportResult r = reimportModelUsers(&root, fbx, nullptr);
    CHECK(r.reimported == 1);
    CHECK(r.skipped == 0);

    const SkinnedMesh* nuevo = go->getSkinnedMesh();
    CHECK(nuevo != nullptr);
    if (!nuevo) return;
    CHECK(nuevo != mesh.get());                                        // new mesh, not the old one
    float extentDespues = 0.0f;
    for (const SkinnedVertex& v : nuevo->skinnedVertices)
        extentDespues = std::max(extentDespues, std::abs(v.position.x));
    CHECK(std::abs(extentDespues - 2.0f * extentAntes) <= 1e-3f * std::max(1.0f, extentAntes));

    CHECK(nuevo->animationSources.size() == 2u);
    if (nuevo->animationSources.size() == 2u)
    {
        CHECK(nuevo->animationSources[0].builtin);
        CHECK(nuevo->animationSources[0].clipNames[0] == "CaminarRenombrado");
        CHECK(!nuevo->animationSources[1].builtin);
        CHECK(nuevo->animationSources[1].clipNames[0] == "SaltoRenombrado");
    }
    CHECK(go->getAnimator()->states()[0].clipIndex >= 0);              // rebindClips resolved it
}

// Finding from the final reviewer: an FBX used only as an external animation source
// (the Mixamo flow that the README documents) is also "used" by the character.
// Without this, setting the scale on the animation FBX said "0 objects" and the
// character was left with the root translations at another scale.
static const BoneKeyframe* firstPosKeyOfClip(const SkinnedMesh& m, const std::string& clipName)
{
    for (const AnimationClip& c : m.animationClips)
    {
        if (c.name != clipName) continue;
        for (const BoneChannel& ch : c.channels)
            if (!ch.posKeys.empty()) return &ch.posKeys[0];
    }
    return nullptr;
}

static void test_reimport_also_reloads_characters_that_use_the_fbx_as_animation_source()
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / "dt_cb_reimport_animsource";
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    const fs::path character = d / "char.fbx";
    const fs::path anim      = d / "anim.fbx";
    fs::copy_file("assets/modelAnimation.fbx", character, fs::copy_options::overwrite_existing, ec);
    CHECK(!ec);
    fs::copy_file("assets/modelAnimation.fbx", anim, fs::copy_options::overwrite_existing, ec);
    CHECK(!ec);

    auto mesh = std::make_shared<SkinnedMesh>(ModelLoader::loadSkinned(character.string()));
    std::vector<std::string> w;
    CHECK(addAnimationSource(*mesh, anim.string(), w));
    CHECK(mesh->animationSources.size() == 2u);
    if (mesh->animationSources.size() != 2u) return;
    const std::string externalClip = mesh->animationSources[1].clipNames[0];
    const BoneKeyframe* antes = firstPosKeyOfClip(*mesh, externalClip);
    CHECK(antes != nullptr);
    if (!antes) return;
    const glm::vec3 keyAntes = antes->value;
    float extentAntes = 0.0f;
    for (const SkinnedVertex& v : mesh->skinnedVertices) extentAntes = std::max(extentAntes, std::abs(v.position.x));

    GameObject root("root");
    GameObject* go = root.addChild("Personaje");
    go->setMesh(mesh);

    // Scale ONLY on the animation file.
    ModelImportSettings s;
    s.scale = 2.0f;
    std::string err;
    CHECK(saveModelImportSettings(anim, s, &err));

    const ModelReimportResult r = reimportModelUsers(&root, anim, nullptr);
    CHECK(r.reimported == 1);

    const SkinnedMesh* nuevo = go->getSkinnedMesh();
    CHECK(nuevo != nullptr);
    if (!nuevo) return;
    const BoneKeyframe* despues = firstPosKeyOfClip(*nuevo, externalClip);
    CHECK(despues != nullptr);
    if (despues)
        CHECK(std::abs(despues->value.y - 2.0f * keyAntes.y) <= 1e-3f * std::max(1.0f, std::abs(keyAntes.y)) &&
              std::abs(despues->value.z - 2.0f * keyAntes.z) <= 1e-3f * std::max(1.0f, std::abs(keyAntes.z)));
    // The character's mesh does NOT change: its own sidecar does not exist.
    float extentDespues = 0.0f;
    for (const SkinnedVertex& v : nuevo->skinnedVertices) extentDespues = std::max(extentDespues, std::abs(v.position.x));
    CHECK(extentDespues == extentAntes);

    // An FBX that nobody uses still touches nothing.
    const ModelReimportResult otro = reimportModelUsers(&root, d / "otro.fbx", nullptr);
    CHECK(otro.reimported == 0 && otro.skipped == 0);
}

// Review Focus 2: per-piece reimport. Each object reloads ITS piece; the one with a
// piece that no longer exists keeps its mesh and there is a warning.
static void test_reimport_missing_piece_keeps_the_old_mesh()
{
    const fs::path dir = fs::temp_directory_path() / "dt_reimport_pieces";
    fs::create_directories(dir);
    const fs::path gltf = dir / "casa.gltf";
    dt_fixture::writeThreePieceGltf(gltf);

    Scene scene("Test");
    GameObject* a = scene.addGameObject("A");
    GameObject* b = scene.addGameObject("B");
    GameObject* x = scene.addGameObject("X");
    auto old = std::make_shared<Mesh>(); old->sourcePath = gltf.string(); old->name = "vieja";
    auto pa = std::make_shared<Mesh>(*old); pa->piece = 0;
    auto pb = std::make_shared<Mesh>(*old); pb->piece = 1;
    auto px = std::make_shared<Mesh>(*old); px->piece = 9;      // does not exist in the file
    a->setMesh(pa); b->setMesh(pb); x->setMesh(px);

    const ModelReimportResult r = reimportModelUsers(&scene.getRoot(), gltf, nullptr);
    CHECK(a->getMesh()->piece == 0 && !a->getMesh()->vertices.empty());
    CHECK(b->getMesh()->piece == 1 && !b->getMesh()->vertices.empty());
    CHECK(x->getMesh()->name == "vieja");                          // intact
    CHECK(!r.warnings.empty());
}

// Final review: the sidecar scale enters the translation of each piece when
// doing Add Mesh (collectPieces) and from there the child's localTransform. A
// reimport with another scale has to take the translations along too, or the
// model falls apart: each piece shrinks around its origin and stays where
// it was. Only the children of a piece group are moved (file with > 1
// piece AND parent with >= 2 children of that sourcePath); a loose object with
// piece 0 was placed by the user and is not touched.
static void test_reimport_scales_the_translations_of_a_piece_group()
{
    const fs::path dir = fs::temp_directory_path() / "dt_reimport_piece_scale";
    fs::create_directories(dir);
    const fs::path gltf = dir / "casa.gltf";
    dt_fixture::writeThreePieceGltf(gltf);

    Scene scene("Test");
    GameObject* casa  = scene.addGameObject("Casa");
    casa->localTransform = glm::translate(glm::mat4(1.0f), glm::vec3(100, 0, 0));
    GameObject* a     = scene.addGameObject("A", casa);
    GameObject* b     = scene.addGameObject("B", casa);
    GameObject* suelto = scene.addGameObject("Suelto");
    auto old = std::make_shared<Mesh>(); old->sourcePath = gltf.string();
    auto pa = std::make_shared<Mesh>(*old); pa->piece = 0;
    auto pb = std::make_shared<Mesh>(*old); pb->piece = 1;
    auto ps = std::make_shared<Mesh>(*old); ps->piece = 0;
    a->setMesh(pa); b->setMesh(pb); suelto->setMesh(ps);
    a->localTransform      = glm::translate(glm::mat4(1.0f), glm::vec3(5, 0, 0));
    b->localTransform      = glm::translate(glm::mat4(1.0f), glm::vec3(0, 1, -3)) *
                             glm::scale(glm::mat4(1.0f), glm::vec3(2.0f));
    suelto->localTransform = glm::translate(glm::mat4(1.0f), glm::vec3(7, 8, 9));
    scene.getRoot().updateWorldTransforms();

    const ModelReimportResult r = reimportModelUsers(&scene.getRoot(), gltf, nullptr, 2.0f);
    CHECK(r.reimported == 3);
    auto near3 = [](const glm::vec4& v, const glm::vec3& q) { return glm::length(glm::vec3(v) - q) < 1e-4f; };
    CHECK(near3(a->localTransform[3], { 10, 0, 0 }));
    CHECK(near3(b->localTransform[3], { 0, 2, -6 }));
    CHECK(std::abs(b->localTransform[1].y - 2.0f) < 1e-4f);         // the piece's scale does not change
    CHECK(near3(a->worldTransform[3], { 110, 0, 0 }));              // world recalculated
    CHECK(near3(suelto->localTransform[3], { 7, 8, 9 }));           // loose: intact
    CHECK(near3(casa->localTransform[3], { 100, 0, 0 }));           // the parent is not touched either

    // Ratio 1 (reimport without a scale change): nothing moves.
    reimportModelUsers(&scene.getRoot(), gltf, nullptr);
    CHECK(near3(a->localTransform[3], { 10, 0, 0 }));
}

// ── applyModelImportSettings ─────────────────────────────────────────────────

// The new/old ratio that arrives at the reimport is computed from the scale that
// there was BEFORE writing the sidecar and the one that remains AFTER (already clamped).
static void test_apply_model_passes_the_scale_ratio()
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / "dt_cb_apply_model_ratio";
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    const fs::path fbx = d / "nave.fbx";
    std::ofstream(fbx) << "fbx";

    ModelImportSettings s;
    s.scale = 0.5f;
    std::string err;
    CHECK(saveModelImportSettings(fbx, s, &err));

    float ratio = 0.0f;
    ModelImportSettings nuevo;                                   // scale 1: deletes the sidecar
    const ModelImportApplyResult r = applyModelImportSettings(
        fbx, nuevo, [&](const fs::path&, float k) { ratio = k; return 1; });
    CHECK(r.ok);
    CHECK(std::abs(ratio - 2.0f) < 1e-6f);

    nuevo.scale = 0.01f;
    applyModelImportSettings(fbx, nuevo, [&](const fs::path&, float k) { ratio = k; return 1; });
    CHECK(std::abs(ratio - 0.01f) < 1e-6f);
}

static void test_apply_model_writes_sidecar_and_reimports_once()
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / "dt_cb_apply_model";
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    const fs::path fbx = d / "nave.fbx";
    std::ofstream(fbx) << "fbx";

    ModelImportSettings s;
    s.scale = 0.5f;
    int calls = 0;
    fs::path seen;
    const ModelImportApplyResult r = applyModelImportSettings(
        fbx, s, [&](const fs::path& p, float) { ++calls; seen = p; return 3; });
    CHECK(r.ok);
    CHECK(r.error.empty());
    CHECK(r.refreshed == 3);
    CHECK(calls == 1);
    CHECK(seen == fbx);
    CHECK(loadModelImportSettings(fbx) == s);
}

// A write failure reloads nothing and the modal shows the error.
static void test_apply_model_write_failure_does_not_reimport()
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / "dt_cb_apply_model_fail";
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    const fs::path fbx = d / "carpeta_que_no_existe" / "nave.fbx";

    ModelImportSettings s;
    s.scale = 0.5f;
    int calls = 0;
    const ModelImportApplyResult r = applyModelImportSettings(
        fbx, s, [&](const fs::path&, float) { ++calls; return 1; });
    CHECK(!r.ok);
    CHECK(!r.error.empty());
    CHECK(calls == 0);
    CHECK(r.refreshed == 0);
}

// Without reimport (tests, or without a scene) it only writes.
static void test_apply_model_without_reimport_only_writes()
{
    std::error_code ec;
    const fs::path d = fs::temp_directory_path(ec) / "dt_cb_apply_model_plain";
    fs::remove_all(d, ec);
    fs::create_directories(d, ec);
    const fs::path fbx = d / "nave.fbx";
    std::ofstream(fbx) << "fbx";

    ModelImportSettings s;
    s.flipUVs = false;
    const ModelImportApplyResult r = applyModelImportSettings(fbx, s, nullptr);
    CHECK(r.ok);
    CHECK(r.refreshed == 0);
    CHECK(loadModelImportSettings(fbx) == s);
}

int main()
{
    test_reimport_also_reloads_characters_that_use_the_fbx_as_animation_source();
    test_apply_model_writes_sidecar_and_reimports_once();
    test_apply_model_passes_the_scale_ratio();
    test_reimport_scales_the_translations_of_a_piece_group();
    test_apply_model_write_failure_does_not_reimport();
    test_apply_model_without_reimport_only_writes();
    test_reimport_replaces_the_meshes_of_that_fbx_only();
    test_reimport_of_an_unloadable_fbx_leaves_the_objects_intact();
    test_reimport_without_users_is_a_noop();
    test_reimport_skips_an_object_with_a_pending_load();
    test_reimport_skinned_keeps_the_animation_config_and_rebinds();
    test_reimport_missing_piece_keeps_the_old_mesh();
    test_classify_material_extension();
    test_material_is_draggable();
    test_accept_or_import_mat_texture_imports_external_path();
    test_accept_or_import_mat_texture_leaves_internal_path();
    test_accept_or_import_mat_texture_without_project_passes_through();
    test_unique_material_name();
    test_apply_material_asset_writes_and_refreshes_all_users();
    test_apply_material_asset_albedo_survives_reopen();
    test_apply_material_asset_write_failure_rebuilds_nothing();
    test_apply_audio_writes_sidecar_and_refreshes_once();
    test_apply_audio_write_failure_does_not_refresh();
    test_apply_audio_without_audio_manager_still_writes();
    test_import_settings_menu_kind();
    test_apply_writes_sidecar_and_rebuilds_only_users();
    test_apply_reports_write_failure_and_rebuilds_nothing();
    test_apply_without_renderer_still_writes();
    test_list_hides_import_sidecars();
    test_move_asset_carries_sidecar();
    test_move_asset_rewrites_mat_relative_texture();
    test_move_asset_rejects_when_destination_sidecar_exists();
    test_rename_asset_file_carries_sidecar_and_rejects_conflict();
    test_rename_asset_file_case_only_is_not_a_sidecar_conflict();
    test_remove_asset_path_removes_sidecar();
    fs::path root = makeFixture();
    test_filters_noise(root);
    test_hides_build_tree_by_content(root);
    test_generic_name_without_cache_is_visible(root);
    test_empty_dir(root);
    test_missing_dir(root);
    test_path_is_file(root);
    test_count_references_finds_skinned_material_texture();
    test_rename_rewrites_skinned_material_path();
    test_detach_clears_skinned_material_path();
    test_rename_rewrites_material_override_path();
    test_detach_clears_material_override_path();
    test_detach_clears_material_override_baseline();
    test_rename_rewrites_material_override_baseline();
    test_count_references_finds_mat_asset();
    test_rename_rewrites_mat_asset_path();
    test_rename_leaves_other_mat_asset_untouched();
    test_detach_clears_mat_asset_and_falls_back_to_model();
    test_import_dropped_files_into(root);
    test_classify_asset();
    test_asset_matches_filter();
    test_unique_folder_name(root);
    test_breadcrumb_segments(root);
    test_move_asset(root);
    test_apply_asset_click();
    test_prune_selection();
    test_list_visible_entries(root);
    test_nearest_existing_dir(root);
    std::error_code ec;
    fs::remove_all(root, ec);
    if (g_failures == 0) std::printf("ALL CONTENT BROWSER TESTS PASSED\n");
    std::fflush(stdout);
    return g_failures == 0 ? 0 : 1;
}
